services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=tpdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=tpdb'
    ports:
      - '5432:5432'
    volumes:
      - local_pgdata:/var/lib/postgresql/data
volumes:
  local_pgdata:
